services:
  epaper:
    build: .
    platform: linux/arm64
    container_name: epaper
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=America/New_York
      - PYTHONPATH=/opt/epd-library-python
    volumes:
      - ./app:/app
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
      - /dev/gpiomem:/dev/gpiomem
    working_dir: /app
    command: ["python3", "main.py"]
